version: "3"
services:
    cashier-service:
      build: .
      restart: always
      volumes:
        - .:/app
      ports:
        - 5000:5000
      environment:
        PORT: 5000
      networks:
        - default

networks:
  default: